---
- hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == 'Debian'
    - name: Create common config directory
      file:
        path: "{{ common_directory_config }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
  roles:
    - calvinbui.ansible_nfs_client
    - calvinbui.ansible_docker
    - calvinbui.ansible_pip
    - calvinbui.ansible_docker_network
    - calvinbui.ansible_traefik
    - calvinbui.ansible_mariadb_docker
    - calvinbui.ansible_piwigo_docker
    - calvinbui.ansible_datadog
  post_tasks:
    - name: Symlink Photos folder to Piwigo's Galleries (paths are within container)
      file:
        src: "/photos"
        dest: "{{ common_directory_config }}/piwigo/www/gallery/photos"
        state: link
