---

piwigo_name: piwigo
piwigo_image: linuxserver/piwigo
piwigo_ports:
  - 80:80
piwigo_volumes:
  - "{{ common_directory_config }}/piwigo:/config"
  - "{{ common_directory_photos }}:/photos"
piwigo_environment_variables:
  PUID: "{{ common_user_id }}"
  PGID: "{{ common_root_group }}"
  TZ: "Australia/Sydney"

piwigo_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  labels:
    traefik.frontend.rule: "Host:{{ common_tld }}"
    # HSTS
    traefik.frontend.headers.STSSeconds: "31536000"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
